[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  
[[plugins]]
package = "@netlify/plugin-sitemap"

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
  package = "netlify-plugin-js-obfuscator"

  # All inputs are optional, so you can omit this section.
  # Defaults are shown below.
  # You can also refer to `javascript-obfuscator`’s documentation: https://github.com/javascript-obfuscator/javascript-obfuscator.
  [plugins.inputs]
   # Compact code output on one line.
     compact = false
   # Enables numbers conversion to expressions
     numbersToExpressions = true
   # Enables additional code obfuscation through simplification.
     simplify = true
   # Randomly shuffles the stringArray array items
     shuffleStringArray = true
   # Splits literal strings into chunks with length of splitStringsChunkLength option value
     splitStrings = true

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
	
	baseUrl = "https://anonbd.men"
	sitemapPath = "/sitemap.xml"
	ignorePeriod = 0
	providers = [
		"google",
		"yandex"
	]
[[plugins]]
  package = "netlify-plugin-inline-critical-css"

  # All inputs are optional, so you can omit this section.
  # Defaults are shown below.
  [plugins.inputs]
    # A filter used to target specific files in the publish directory. Be sure to only target HTML files. This option is passed onto the readdirp library, see https://github.com/paulmillr/readdirp#options for more info.
    fileFilter = ["*.html"]

    # A filter used to target or ignore specific directories in the publish directory. This option is passed onto the readdirp library, see https://github.com/paulmillr/readdirp#options for more info.
    directoryFilter = ["!node_modules"]

    # You can refer to `critical`’s documentation: https://github.com/addyosmani/critical for all options below.
    # Whether to remove the inlined styles from any stylesheet referenced in the HTML. Use with caution. Removing the critical CSS per page results in a unique async loaded CSS file for every page, meaning you can’t rely on cache across multiple pages.
    extract = false

    # An array of objects containing `width` and `height` properties to deliver critical CSS for multiple screen resolutions.
    dimensions = [
      { width = 414, height = 896 },
      { width = 1920, height = 1080 }
    ]

